### ISSUE TITLE
Why is there a need for input binarization?

### ISSUE THREAD

**Issue by tuanpham96** [Laborieux-Axel/SynapticMetaplasticityBNN#1]
Hi, 
I'm trying to understand why there's a need to binarize inputs here. In the supplemental of the paper, Supp-Algo-1, it is said that input is not binarized for the `forward` step. Plus, at the end of the loop (only except for the final layer), there's already a `Sign` activation step, which I assume is just an output binarization. In essence, is this just redudant?
 
https://github.com/Laborieux-Axel/SynapticMetaplasticityBNN/blob/b1891e5c760f16e1cb51d40a26ca6b9718b21ca4/Continual_Learning_Fig-2abcdefgh-3abcd-5cde/models_utils.py#L43-L44

Thanks!

**Comment by Laborieux-Axel** [comment]
Hi,
Thanks for your message! 
The input is indeed not binarized since at the input the size is 784 (on MNIST-like tasks), so this binarization step is not applied at the input.
Otherwise you are right that this step is redundant the sign activation in the forward method, and can thus be removed.

**Comment by tuanpham96** [comment]
Awesome. Thanks for your answer!
